[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "72b7e6c76e8f8551ecf7cd06656f4bdf5ea0c4d4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7b72a5869bae8610199a62bee9fcc284df389a1526b93d925990ffeb3ea34507"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "9ad5dd7a673bd2ba629605293134eb9d6da974ba"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4862e36fdf1ae5c1c7929f96f1140b5d076460263c23e9bdf5d59a038dc15846"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "bb5a783b127779cd7b53e2304b72a7027b6cd088"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0c107afce06040bac52385a4604577e50d4c26faee5201f4bdc2647a4fe54209"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "855c0d947ecbb38ecf5a5bb1749226db81add2b0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "19e5de09e2c15df17b922d3ae2726509f0c77e1e5817d3bb6bec031aeb572d5c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "cd89b5b69ad29982a249e3b0efbebb67c34ace72"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "17e6b158eb01be95ab56e27eed79f623bfcaa1cc56dda1d949af03d79e9c50e1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "77976c6290d0877f1a810844c6e5df2270b5c2a3"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "ee8ec5677e37c76a83472d8596384a3b2769a9c28c8f2e5531a4c7a053da27f2"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "39280b2b765168fda762f9ee96b6d53cc7beaa85"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "70604a240c23a8685bd9347a4df4270c5afc344056e2bfa784ce6a7ef9f8c2fb"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "9287a7e78818158a8d812c5ab1ee622d8f8c0dcb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a3d621e5573e8130b04ef320088099ab8cf03637b923e0ba18ffe792bc20bf9b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.arm-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "d4fa0d678113bd571f80c17c867582648cce3f6f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "524820652c973f14da09aee247905db8805f3e585b2b77d0de3569408e7746f8"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.arm-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "f136d6f6f9a6c8070c1cfff8e5c6a3ac7d7a88c4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "fa5683a88858888ea0c702f830987d58622e068455c41c62f75a88b0736567b3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "fa2afbc376c0781c0775c8f212353e2c9b442509"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "76c40b90f1d1fd47c61fa4be1cf849a100ab58c03ec700acd918775ced7ae66a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "affa2d7e04365986e47143df7275f41f22dc0e28"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "1a83d04d37cbadf4bed76d583e67c4f5dfac86641f4b705ccf87bdf6bd05a27b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "bf306ab98e0390c7cbcb4c110824a0c16cbad9b0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4b8fc707af2069260abda6737b2360449a93557ace2b8d33d36c41adbf84792c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.arm-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "36b801dc95df8f117a9ec4350c02ec90b6a6e3cd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "b9ccdac3766edfc42cdead5d2788522b2bc382a515e7a0c58b9ee956c57a0a86"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "b2a77bd0f31731dc8f4d7402bf082ba097641d56"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "43185196a849bffa21978749b99442b3a89f8460280b624355d7b69071692be5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "400b37945d16f5585217031f13381d3c3432d9e0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a462d151b23c72a9301c69961b93be8cbff8f054fab83d1d84bd30e24e63238c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.arm-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "099b480448718d09c00f8fbce4c02be7f69aa9f4"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "2c7870e7fb4f830664773e9b4d6ee452eea6b5cf8630e7e7f8058432bad9372f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "1fbf2d150c9fd8e3c493dc0d05663260e8115058"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "fe1f0b5f20ed40a838f184d2898867680079da79d09ffc4ecce4284bd713d0a7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.arm-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "1e75a2f06c22db6470325a1565e24a5b59d521b4"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "a6c6407ccdadd3e6aabb007e6b26e021f11c09a4f8798dc586f5d41797bfebb1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "f1788228b5ae857e71396cda3942d0eca7332825"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "a40a9d0c2077149498447bc00b57dfcc1884712fc2a039fcad8e2122c991e9eb"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "67174ada0a21a4d8cc07b765c035e8038797f2d2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "078ac94a10518993ef277805a3599253727b40397ffa4dbb97f04c103ac51044"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "491f7572fa3fb7791517451214c09d0f20c503b7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "5693158c2b1f0cc8ce6a514d237233b47738ac9557582a083eb5a9b7ebd2b808"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "fbbd9a9df0909ea5b28c6e7c55a710b220a12cc5"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "3f619de1adc1a1b5f8ad3c6722d9138a10b27f1b8526a86e5acfcc661dba4549"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "9f498ad33b55e3279edb3ee9dba91fe8d9e5d345"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "3eb0cec61e1ac5aee3f90620cb314887b6be21d97de3f9d3bc10c2bd88224350"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "26e77e2435e4289dcda3854cf1001b390bf22ebd"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "69467d74df1929490af6d147a7a98c94df25b956c5cce404d4a12c9319e81cac"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "a938c763368fa8bb1a324ca0933bb2a5e415fe32"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "d2b7277632419afee46dd95f0b53ef18a03d8ffc21bb138d022c59662871cf9a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "8218fa72a836b4b617643050b9a927f419090d67"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "76e00f7821f660426383ff4f732f172da4782fd3be0df051d46544863d1debb3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "5b72a2ba03b06d0778f03461e36bda7638e1fce7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ea319ae3bc1f4e8da84ef22eee0063f8bb5e05ba561bdeeec5b0704c0512fd57"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.arm-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "113c12708abb3131196a96a8999bcd72f68d91bb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "3aa0e8b0c7ef79f4f4bcee9dd8e7b7ce2af929764d0db0779a737c239bb2d9bf"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "82cdafd39b8491abebc311a2d71bd9c32051932a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0c783431b25dac7f25d1eae83890e79fada57624348d13b3939c2d572498f014"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d183ef37b3d2398c62ee222efd3bd039519e6014"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "d161df1d470ba6694361f1b5b1f68781f8984f8c6bfebf5a32c7f7b48e9ceb4d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "f50adcfca6bd0a6c5bc4c2938c057e739654b77a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "2959c0c4a828b6855968f57ce68334717884907a69fc11a36ff49a1fe8a887a8"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "4756e97be70708ea6af4e1fb73d0f78adec183cc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "95a9256a833bf39606738055f76891d7c3988a494cc04f25b77deb925ff4d2ee"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "ca632990c809b1f683845c8019940dfe8f9989df"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "72ac5067f2790cdf1ad5ad0e37c3a23d0f7ab20ef310bbe0350f2868b787573f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "a86b2b9df4ffb9831df47953f87f729656616184"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "046cbebfb750f906cc9ae49eba67132de801f61c5b4d6bd3ee78677670a7ab49"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "7828b21ca55e1dc3141bf3f87c86f83dec3747d0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4f383e0ea4420bca49750270846e939af445e5721f3befcddebac9a92ed30367"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "780c4ad519be563d85db65981339069708cbf0fa"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "9e7c3fbaa6b639b90276cea7fb8d634bd05d9a09b789f7a883ccf63502d422f5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "58c6eb8c5d31935c09833ac85f1641f153a07c39"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "0f65aa5402f106ab28db36c1674c7a8f98873abb0e50aa90b7bd4aa55e8af6ba"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "f9a6b4af9adbf5258f37760edeab37ae30dc75be"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "add393cf5f58f3c11d7f0821ae574ad32b491065d568392cebdd1d229ff2ed2d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+1/Arpack.v3.5.0.i686-linux-musl-libgfortran4.tar.gz"
