[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "fc410ff837a7f30ba37bb6621728e2df242330cb"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "a19f7660731b942ad71ac8e0272338fefaa216b12345a191963e8cc43e55b2d3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "eaebcd8941c5657fc71e86c870bea10a4d1a99c7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "3fb73df41754336fbb19321439aee9b315eb9560d5cab0969bbdaa45b45e0caf"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "654d910878bdc578fa29b2ffd3f096566f6e2948"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7e666ae80f5acec27e391e2659a3c5b94be68d5896ccb72e5826b7f326b2360a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "8b48cbe6e3f6be66f1f20a5c23d38a0a76569dc8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "b304b27c00f003c9ad8b697c9dbda0b4ae0c16c3a99d38abe99acc21b8efe39b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "b59d625f292ecd502da8cc15411debd417cf204a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "80fef404fedee5863cbdc875bab397d0b91de1f9ce60978d2fbe4c03cead220f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "91d6705d4d9650b80b5c8f28eb9fc72d423567d6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "05c5dfe2f65cc538e09a6a411b15988702d48855a737abebb51122cf3abf922c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "7d40330e6db80d044d31948c2d3fa11c6a5bd824"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "da76c203a2672e581617f95e428001531ad2a123799bbc9324381b2d18da0aec"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d013970809a47d396c3ce3afa9ff8fa133e13081"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "65dc9b56ec5ae8263f71ec2f48ac8082505761444d9945e560be9a43533d2c68"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "145fdad6a9b80536ea5cd6a357f9477664f00192"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "6f41ae12a0ddfc634aa6e6e94817477d0e1c98fd87be93c43c5a9041adefb79d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4b022535c8f13c24456bdc1143eeb0f999bc4602"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e474ee8adf653f88e2d38ea4fd0b6afba8b7a50bf2d9a936f6ae77ed1170b897"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "902edf0d4c9d88fb18553817a3fe445cc1ca9043"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "44d852902ebeaf2d19d3c9ad0a577206c0514ee9f6265caa7af87b6da132780f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e92c42e0b0d5da2ef1564bff3a25352c5a77b3cf"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "b9ad14b43644ffc3ac476033020db423ba31fdc0bc8126c710c057c92d879fb8"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e38a8e7e149963585bd3a7fca49600a4260cb71f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e8a5a7b5cb590ebe91030fdcf8a5569918fe48fb93ca081912315ef23c91eb81"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "52cf8846d2a0fe054297d178b1bce74d9a423f28"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "481122b1ddfd7b1351828d4e8ac41495410af489887465d0dd54c2d316c1b7e5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b086d2431a3837e4eb7133d5c1a8c27872728c5f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f95cb6913c7ccfc8915ce738081a0ed3a1df46b24f08e17f2976ac5a79a6e8bb"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6d1bc2b229a2286092f7c58ef3b30c4439941cd0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4684d75ac912d7b3059795e9c9e4bc02e9a204b53e7883af9933680248aa0314"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ee86504538439546f1497b62013cafe256ec5eb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e1db621ab4f081585f185fab0ad4d825f873911bdd17f43c8c5e35a31be603d8"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1280c9728698a1f8d7dcec7c98ed73a396a8736"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e95e134ce93c0bdbfaa29884b18f7075a6e41a99db7c92ef87039d40a9daf48f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b62980db62573e7e5f74e6badb4a0590222492e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7346273addf5fbacff635408ac1b2e001ab4a709deebb750a2215888d41859b5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "d3a2caffa3f7e5576943f8c6809a2f45e26ee10d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "720898ffc9afbab03174bc8ac977433c36fcbcc958eef03559d0d02b5be9c535"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "59998b78605ee803ad8601060bfa5498000753df"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "caddb1ff8af4c40537add427b968bb141aa8db79e0e730eddeb9674f3e015f52"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "9c20ede63271520360303adb1c46f4545ae2e112"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "762dd8bc44efe786402114d4eaf40a3959a26dd2dbfc2f094e2f2c5920f57823"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "4e697f26be7495723f622bb9391a2e4e2fef5b94"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "689809d363092a474c402300db62662b4924f7a299a5fea947ac288c98ef7f98"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "6c582da4441e93c5811867582025e763364fdf8a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "6226e9d7a29d0f1b9c69d29026ee365b1234e7d3bb675fbda60dd525c164f531"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "f75b9cf7c062cdad9001e218468ef2c3401de845"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "515ec889d2c8a27808580b93231fe6e14de3f07afc024b33e85e1b915e530f18"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "31c7e088bc76b9eeb8f75fa8924d75004555471c"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "195d015ac685920e4f4fd1b3c1765ef06f892faa9d683045b345408e7141f946"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "7269d6d48d3dfc2c78248ef9ac4e59911056b124"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "7dbae4e59e906ceb1a313e16e2e18e45b5ec945c9af0d5013cbdaf5a69873ca9"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "c5a17218225e4989ccf5b770b29b8d0e5853a63e"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "f2934b275764f1b9a8e870181caf1c7adf6bd1165ec6fb05e5b650d4c1e2db34"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "cac34c6213ad68d0ca9354e047b24e2debad56fc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "55ef9821322279ee3a1f616f93b2c0c7d5270199a11f407b61d8ce1a91d57d66"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "2f17713152bbc9caefdd62948a59fe55132d8fa4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "2a3ca2e6d1d06583385aece42efc0bcd52b4f0a6a9358d98dd84922cf2d8eb32"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "8ed0601cb9c4958069f2ec315991f380c339b7ed"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "85a72ec2a0d90a7f69ce6592c1ab3e8b14a2aef597e37d2a1e91522e51e1b9b7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "aa883d2f1a6e49501a41bc5680753c71d8624bf7"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "372993b97b75178effe2f155787e290eda98d83bf285b59dc7d67d231bd942ee"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "2c84ccf1620394d09b9b6939e1ca7fa18ffbaba8"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "9bc98b45d0980c75622e487a841d2c71e4ef205a3ff48f889c3b379817875618"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "6d7d2d27823a1d5aef81e4bda49f9fc85b05b00c"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "fb6a227da30ca1c5341a745d226b4aa6dd078b8da045af055f87d465384f5be9"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "6e37b6c2d5ecc7ea89d63eea173cb8993796d26a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "cf6fffcdac4932b67b7aa3caae137533957472b32c9c17146145106d2607527d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "3f2200565f7a718086de82c49836b8aa023fa284"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "cee7e1253e56de2526201e5add3ed9c003eb09776cd9c83df6733c99019a0467"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "b694ec473b6e4726095b2cd71d869c9db78de9c3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "61c9ff4989960a3370fc355634762b9701fa5383d864478ec36cbfed7e1e5cf8"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "ef303158ba3a83fe5e9fe74853ef3685e3a512a3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7d750c77c41f14a93f63c1f6f1e2760493e7d5bc7f90c3f93d867176e8fe45fd"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "a1469d2785ccc3b5fceff6e699cbc9cba18a5d69"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "add05344cd3f57da52dafa2fc9a4a4c910f1f87dc44912728148e2400546e4ea"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "0184a6d7c4d02c69418013b17891e5f9adfb8edc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "51a23201bcd284d93ee8db2cc8d6af847ed29458f74280bd56883fa96748b4d4"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "927b1d9dcfa6784cb8dfac5da9dbb8dfd90f8fdd"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "16e19f7ff0b80d11615331ac0621c52d134bbaea2534a641bcafb3e6d9b88750"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "e7a9ac20ae989810f69fdad8e5a45315ca6d19b9"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "e509e01fb4f943282f665e337b46183dc3debe221830d9fba9feb83eba152855"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d39e944c4b79739cda3e3ee1ff73a788895061b7"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "73d23b5742ab4df8634fca092f788fa2b3d93cbd4756670f103a9b66b63f33fa"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "457e05f28ebdb6918c40def3ae0d89c054ad873a"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "550785e9aee4cbf2cd0d0f3e8c71910131d0e7221a0119e9ed87f0904fb40bf0"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "a6f4a19c986a6c9af58b5e275effda1ebef7e07e"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "ae2a5c29028d064fbeced6810b2cd89b33a21b7b2a988c82f4a9caf18ce26e46"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "6a6f16a73e1928fa55cdb855da6d338dff78855e"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "8604e09343d5bf65026ba1ebf36ae0b42d046a708f24ab71803ffae55b9a0ffe"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
