[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "c465e5392ee0f436fb4da8d756f23481f5681d91"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "3e503a69a7e4b346586d51ab43b742ac9a9287f4ca2ba87e26619f1c6c59ee02"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "1b8d3e69a72b23b4b7fd4099e91db484be2ea3a7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "89aa969d0e44e7d1c83424aac902767a8abdbf6e58858f1b7f5a44bced1ea2cc"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.arm-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "aa7e5f4d703ee1f101238802618faa9b2e58996a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a92bf3a9b4f03d58dd53b3891e987450ead8136917da8023adb0b3e1ebb957e5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "5ef7a4fc50d22e6622654c584f583c6258b3492b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a8976c0471e07c8db4d2f97911515383fadf445415dc6e62c713602e48d83638"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.arm-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "cbf20762addf2232695bab10abac9043f853a6c1"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "f46f73e1a5abd1fadb47e96dd44a9b467bddd06216f13ea1a012a8ececc50791"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "f3cd8787280cf50c1a2559e9c026f027c147675d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "60809588c6c9e01ca1214696b510c799a30c2bbb83aa2f1bdfed8d389c8a1671"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.arm-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "e95ebb87bf7853e27ee4c10dc8233e6d5e9b6de8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c97602e6ce773bcb8410d2458591ccf81d5bdf17e1d61f22f0d398983d0b1f1b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "2634d169b580b12a05586d72628c1e7f01519e4d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "3ad4b920a66c3f0829207b94a5e72b99869c13ba8d30a9b584dc521926e788d0"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "c414710a89bce9626ce0f6043da7b754bfe8df8f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "d3e9534781ba6df596389633b8392c3678468b6837d6d7fc4c27ac808a052eca"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "87d6f4a84013869338f682d960bfddf62f838082"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "5e5a246871ca255d4489d3d99519fbc63d2048d6b751c96f076c8e8aa295706f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.i686-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "468dfbddcf644094ad81824d9567f246f396e41f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4873282b20db4a5773c18ed17f0856d20092ef92ef021a08a649d3e04d15bb04"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "19d1806244622b11906f30865a8f7ecd457a9211"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "343dc9899f399e8c69ce8ccdf13540ce97c554020117ddd1ebae07edc8875413"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "d8e7301c37a8adf50e3cd7435898b6152c11c547"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "b46870656383e0961482360ab23c5cdbb59714beddbb08f7876d146315d2f9ef"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "927fea1c38202798bbfd9f2919a51fcc2caeebc4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "29582f5772d769180162eba8f42edf4d9c583545e61c02a1d8d0a88aa06f6d53"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "46ab3ff6fe2960f93bd71ca6236455347e722886"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "d14e7df7eb4112aaca41fe3936de4b251f43aa69d1af70955b155006ce27cf5c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "106bd9872c2bb7398310adc6b3963bef31d2d1cd"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "6c8eae4d87710e2175861955feff02063a28ec11b30eb6e39622f7b7662b92eb"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d6eecd36aca378b299787df6b672761672cff0cb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "99dae07a0f692a272478d29d7a97847a1b7be57c1cdae825ee9e042b3df5671a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "4215371b44a7b63488612f60389a19cfcc9b0dd9"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "df815ac1f3779a53f595a0133d8e94cf565550c2aa5e81a17f0fd6ebcd448af5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "4737837271fcbb2850b6af4ae4a86701134a4147"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "61af510a4c88049d40c6bae82b6331e7b94240861851498d1759548beb4467f6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "2490f3df22b24826a1be5578794cc542859d31d5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8b9537770b1ad9ffb03763771f6b742f81ee0413a09a5600b1a30f2edce089b8"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d451101daae9ea38ecf867e0bd955adf44bd54a8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8ddfb7b62a3685965d661360826a38399568352217369b15fb7f8e2a5f058d20"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "2263b6331bbe26b84e2c4e1cdb0ed6fc13c7b911"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e09f96dc6da3e69d10d429f1f9ab9f0216eea619fc18072d81887ab59f630f67"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.arm-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "092d08a7368507ce8d89d3fa67c649c5de64052c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c032c8f70337af5b95ab3437ff5d0cb3fc69c8e9cdd57c3999172d25fad049c9"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "7166a1cc8badbd3e4cd854642a316f3495c321ac"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "53ea52eacdeee1ed63fa6bf889ad8b4e6b9fe2f8c13d158dab7f243774542730"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "23da02558f6146ef931d9d4c025666b672720c83"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f9667896ef752cfb19b7cae29f4bd6e5689f6dba3717d47f865ba87034dfc38d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "a137c11d0748a29392782b69d4bc5e61d0e552f1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e4a04c0b1f64ce98c32f42bfd26a25860413b0101843a4125ad73e5fd8bb27db"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "5cdcac90f9a31927331ccbcf4805b7d65c419816"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "5e81c0f585f5cc12fcd13bfdf7d25e0a2a16c7f88b122b4d61ca8f858f52df5a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "8c147790245924047239020ede95d665b1918331"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "9e9d8e6ea38835ffdafe4a7021b6b183b770e90926d0efa3a59d3ed404b59759"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "efcd0429975dafe73bda41d2488b7e1c0f491246"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "211b79fb31c66c02a057cbf1b6f41892d915d96fb31bd263dd9883bf9240138d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "26dd1e47c3f8be2ca3e43f6fbcedce62c86b61c0"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "7d449f7eb021561d5924a3434a9bb208d942c84225320e65137a1850d29eeac1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "fd32081b7f0601839602fc6147d957cb3c3d3436"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "41dccb1bc1aaf0d310c8a1026d8191a48c27a1a60f1753f5fd9020ccafb483fe"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "2ec4bd914849fdf24baf112cfc8a70251006e7d5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "cbf4453c835caa6c7a080c03bb05d23e74cd2f9f54f8c4672a781d15895e8591"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "540168b7a665e4c6ed2e55891518fb6263da8c38"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f89f491c69d7caaa328339d1374a570e104be1ec3cf1ef230a9ee745cf8a3eba"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.arm-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
git-tree-sha1 = "fb9429e4619219a9fa9089a55050d60e837c5980"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "07788dd331c146f79cdf46202cebb9fa1c825f651207a502f5053ebc0389c8a1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.arm-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "3d891b729357dac26ef22ccfe7f08e7f38863b97"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "15ce6123d89e91704e408e2c06a603942fc16bc90513cc210bbd500092e2ff18"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "82d2c97d5d8291995867ec20a22d98f0d0cad655"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "6b79c1cc569ce070bf7c03543f61d30d45f14b59873fc0de874b231301038c6b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "395df24e3d29da0d8fb5d5f4a34445aaaccbab96"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ce47cb63ead98b9869c7bff0fee3bd87c161dd1a98819ceddc454ff39bb3a716"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "68592db2a9a92f59f3c09c1ba7ab45522ef6f72d"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "983ed2b29de1253dfe49dc4cfe619784a0e58b1cf159f074a133fff1475b9753"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "f0e87399f0d6f72d7615739437def2dad1cbfafe"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "178c7c2a834592037d97c79e177e30e49f3590d75c37fbb6f3f275530800b03e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.0+0/Arpack.v3.5.0.i686-w64-mingw32-libgfortran3.tar.gz"
