[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "93552d6678f3bdb151972d5ad594b10f233ddf95"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "f6fac4391a1b0a1b07342ef4ba637798647cc46313607e228bae27f7f12dd137"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "3967d7d08151db92dd9b6825edd8ba06dec56e10"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "2418eaaa4740d17e314561addbd8975875deb2f922e1fc28c8d8419790520bea"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "68ee08a4d43540048540eefe5d34d648f1f1b3b1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4a08112b9e55402e0e35e3b3a0922b196cfc6aeb8458b7bc5621ddd7d1e10e1e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "9b0f9dd1db4dcd5e0594a46f27cd8440ab4855c6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "1548c7131b8b06a67c72b271c08dffd3b322287d8f2a6c8a41c48649b62e1101"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "7d8d976cd13cc5ad4391fe815dacca2bd869a957"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "dbf4980137f0f793804fd9cb2529c6ca6ad01a556b98215507ae7e06d53a153f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "b1f3349786f29a3538fe1c05b98e5cd3f9800e45"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "92193a77236b641a94aa0f6963d651be28eddb63b38ab2772d851d02827d51e6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "99945681738ad0a62d2292490a43dcde241547d0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0525b1dcc7e79039d3c3e43b4342ae7725361d2e07da83f066fae43dce98e7d3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "27dec61baaf8c3a93fbeb5f334b0701ee152b7e1"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "a08d7c28756f1f205384be487d3e056da6c2d05b72bfab0ed7ce0f3e3b9fbd02"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "4da70fd9c81f7d1174662005af0c5c0f4ef2a96f"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "61de829c650000120e98da20335866f25f2ea34830aa5365d71a6e6d7606aac5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4dcfb7136c0f092cf2deb3c90f8cfbbed8eac8d0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8015d339e9b3c3a7b73675b8c100380997de72f9177295fcf44d70b477bab5ea"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c29121a7510d7729ac08c3abc0cd4581b03c99a1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "1c0f7677f4841ad797bf1d55bfaedd8fd88dd64e67f72271d8b58d0dc73d7c1a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "659fb03643e7ae72898cbd4dab5f071ceb7b5391"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e4a634a1b023819337f0b9bc1e129b01d1fd7c03a07ccca72e07c2de0579ddca"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "78ab62e03033f5356ef3e1908c83710709471fc2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "058f958dee615b8ef6da73b68a7d2a5269f7c92bb69eda33b31beaccb3a4efe8"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ae93ce8f03663dfc9c7848ba0cbdf6dcdd02f7f6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "6c799332ca195a5ebae301feb8b755cb2c419ee1b8235f82d41585440155b5af"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4442c0e2954bba6456a1021ba9bf4f4b53d3b4f9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f11ff6c947e91a1a8ab97badab2692a4d0f3f3eb8d0ec446cc496682259a291a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6f925cfc47632f833d5636489b03f5c8d348a369"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c1fadf72a7d8838a946dc6d2c767f6ff29c671cbbdae4d24539ad9851f02d72b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fa06b17ccd974e2c0811dafdd8f13c95bfb689b7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "60001ca2b50ba6a409db7e68dc140777876321c06fe7281f7df26c5d04d1d9b1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab82ebaef547e59be4541632e97c18c92c12162b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "19def373af5cb645350d8d0c97c037f5397a8bfc3de05ada58f4959ec834c31a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "49b07ab99ab04faa3600f2cb0a5431f62f6030a1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c322bf93163cce41aacfe3165d3cccebaa39cb40c6e46e63c7abd83299bcd62d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a043dda77b9ee71443e4e38c37cb25aa38454327"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0ada87e53f65739e82dc372adb7a681dfe5c2ed6426d7d8e8a2d9734e1157245"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bfcac99dd1b5c89d35328b37a7094d43d0f01fa3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "304ea939d49cbf0a14f3a2e339dc2e18090d16c7fb438d90b4c0245b127bfb42"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "ca490e92c7edddbc7f35352fb441d566749b6e0a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "1270d94969a561d5672596635d61fc526a9524e82acf116c70d553c737405ebf"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "3a056baa7fd79438687b3d0d199bef5f85e59842"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "23ae57c87b469480f82ceb01b6f6f5047beee9d2a56fdf466a2835f0a54c0d42"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "ca34b2e4878493acdfee3247e95692462d32fa73"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "672faa4bf607097c2a5040e71e8946aa378ba1b4545b0746b773c5bce0d67f06"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "059779bbc510fdd9d800fcb5d44eb9e657652a2b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7774ce1ebe69c9beee7a8314a21da574d37fa34430f203906f412fcf2c4b5eb1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "e2bd5f973deeb9d0d5df5bc93836495accdb2459"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "fd34f54b5998861fc4b1e65fe83af7429cf7f124965418b831b05492e8d8876b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.i686-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "37cdb810917c40c890338f371126bba5e2302b8b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "933f5b35f9159ecf56d8aa84699086acaa90d20cb7f001e7d53e3d10ab093e53"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "821180a9708e60a924c7adda8f8179a2e47cbbdd"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "207c36dcafbad0470a6d29ef939596753803c55a7873fd8b0bcb99b922052135"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "7f8f7435530c31d631b92529e39bc54945456260"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "df1743b636f514ef9f7191c15fdbd941696306c29a65463f29b49afb30c30678"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "0102098658f44e088b28f1976705e67d7930c267"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "48f68508184c83d3ff44e3d2587c4b66673702f852b638f8b9544d4ac7ee7c0c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "87d5f8f175d3ce1c539495729931d6eee208d4ab"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "1f9c5f14e9a8bd6156f7ada5089c3ef048cebc8afb4dc420e3684af1d9069f3f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "444f7a2d9319dc1aef1ac12fcfbb76bb80597990"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "fd0decd94b1533c28e652d47a8064e3be081528052c12cebc5e3e7d281801507"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "c344091d0129ff3d0b54b1d86e2c7da182b2ec25"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "3d200d4143b38ccc4ca9086d0b88bde5fd10a0ddce623efbd12cd39284e0e544"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "06a7f635188bcf708bab1ea84b8fdbd574f7c044"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "1681850e26270bdec2408e77932f95f944a9da6fa59d3bd9a1fcf5268878e387"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "95c9360f3f4b3893f82e1f5b5cdf1b36c2690e15"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "75f121dc55808f1017edd6d4fb21186638af5bb0d856bb7888e0ac9d4b272038"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "1822f43f2642dbba7f0e54ed2b9c77288b86d18e"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "f7d2b6abe26032314ec2c9c81d5cca6e54b5a2d17c384bf048725510b858f681"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "565aeeebe118f3967f55ff098041d7506f0ecaef"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "6cb1a28e3e6040e466aa8c05e0cb5e2d975ddf3bade1b1de3ee55633a756d2f6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "9e0d2181fb07772d0b6520eb7fd84ee70e866737"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "bfd4dc410db2b789c1f24f5bc7db3e3cfbbc68cb3c6b8288eb349e959c74ecd3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "a5e246fd27c37dc4f30589ffbba3bdcd09ffc8d2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e9c73911b2a458d3e84755871c8eef18e5c86ae66821e81dd47a786e436cd3b0"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "f166e03b2df2811b6d8aa2e249852be6ca78adf7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "514a66b4b70dd0a06e6c660ef23d966e74bd77c2e222431ebf1438daf4bccc77"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "90f740d11ff7942cd554df3e209ceb01aebdcb8c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "26456dd2a3ad4d284ccdb50afd14c4a27439ad8b1820c1c9313972ce3770e3f3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "5fe1e64c00622c2784d19ac9a459bae569df2cfc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "bac383e1af089cab68ffbb315dc4b5a385b9a9aeb4acfadf338fc716c586b66a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "c1895340826e9cb64518a5b7b118f17c0e1a3f4a"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "6479e5734d525a5d8dddcf68a253dbe30c67361ce0ba1a2d9b9301b54bde9caa"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "7b55fc63c2cd43984d9be0bc53f98dff3c4a2867"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "47734f6f69cbe14916911788c70fac02425f6b29f526939a5c9a18e05f86d1b5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "9787a61785041efb97a635aa6f14e10a677f8bde"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "1d81a9ba149d78b32edee33639b8980ee506aa901743a0e31236af83216f8c47"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "9bea8dbcbe62c1695e18505af7e69a3708446051"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "e658d46ee87f07efa21089c74bcf38d953746b5370eda046bb2c712adb358ce6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "fa7e9ec2ce06a454e2fe3922c89d984323feb51b"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "6461523c1d5c1661e8ed5fbbcbcac5fa5aead98188eec0a1d3c280eddadd1bbc"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "6b05e14a6408e204ad68cd4d0214a5358a7ea519"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "04138e0937be275e13ac77ab684e679b8acda7896d7ea0ed9e413c7965265de9"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+3/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
