[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "f1e1b944c74fdfe6f9e949a837469708bf431333"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "ac2dbccc3530be04e3f40ca2d3c99d0c61b455d10128871e00bf57bd3e17e993"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "317f9a9bd310f2a2e3c6943ae28577e4b9c5c68f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "655fd83a50ae9af2f85b1f9adb24b03274413b663aa2f00a7352e40957d6ea87"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "b67624d801c023580e4f59fb0c2667a1ba7b893e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "2e7791e2c81d21c36760400f73a764a3ad3da9c2efe68780c41d2143142de7ad"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "86474e3ba029e126b565f46d2d3549cfdc407f70"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0dbfb26acec462e0044f79b83c688ef6790870bd5694358968ae4310ff41fc38"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "20b83ec0739c8cb1a3a91f89ba39dd737b3ab271"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c6b51688ada50160ddcd9b8ff8104b8b3350ff2a19368824885778f37e9b3e5c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "4c38c71c4d7eca19117afde8a03c02ea178641d2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "985d69723e1604304d24c3e5fc7b8fd3e6aae1887fde271865cb88451a77120d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "f90d9eb8f80f2e8d69e3a1bda3937c29fbe46578"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "94c4ebe449db9e85d70a673d9dcee1db7cae0995d3ef23d5ee28fb5f756d6b07"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "60d08ad21b9e14628eb2756b46c13e91ae02631e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "94bc9c2f9dcf9c59219cb75e369557d0162eb10b4ef2b520799414f5ae6ca484"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d093c638a5c755e3c60f141a5118666de46d987"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "85598e3eb64a524f14e66ad6995608907f87723a68c76d5b260d51966748526d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d693563a142b804ab2f44beaba1d80a68b04a66e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "55a0164b84360e35b8ba20136d35056c866026b439dfe32661eb4db39526bdd0"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5e24a28bc9a4f2bc4d169631995116470d3a94bb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8d0f6f25451aafb1ab597f5950e0d4c9e1565970ad943715bda4b97e25badf5c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fc8032a01aaa25717f3d991bae82a40595f53f4f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c49019ba6891066f24f867436d9dccdc0ea9af59f92ebd7969fe6a4131b1c9f4"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "99dfd79627eaeb32f56ddce232789f6ea18a4266"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "1138f514f5c0ee25cc4181c07d6c22d96e8f1f34369eb3b61d6634d2981a03d1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0026c460270f94279e23fdf8f78fc82cb703b19f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e04436db0ad6a9e2c4de438f7d9f639889684057c400870fcc6a393fd46ad46b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8604c6495aeab6f6d517fecbfe41466e4766aca8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "74df676491e82ff3d8b24e2e31e42c56bb6f17e534d83a80e603ced67996f3b7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9962ef0aa73393c149fa97d85cad10ffe5e0f60a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "2d5be04898b2dc1cd43e25b4fe5c9d1d855f47834a2109320a43c512fdeccd3b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "83fd10e56f60f1990d6b001a20c493a67c53f660"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c2d667da04965ade316ecbf1a90e9a581b53b9e3edea83bed1de0fa20f2e5240"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8ab666940415cb0dfb579af5ab313b4ee9b90904"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "19ff6b9133f2a1d9afb40db62633d4e250f7158b059addfca30e3b30b4dd4ccf"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7ea15a92c13dc55a4c6b9d1f8466f7a2b6ea1f3b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "642f186e88649ceef5cbcee3a08a3e6a01cea046e4d4bbf5fcdd6cff3cad860b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "85a37aae17a9fa5db975f6e20ef42fef1988b69d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "d1dccd7c4a01c5eb17f41f118c56fbc432dd633c2a2c5c664ef35781eef2d1c4"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "4f4d768230879c1c5e91bdef4d5f6994682a33a2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "85e693d8c5f0bbf95629dffcd8804977b6f26da64c6684e31c84a91be2ab2af7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "06f7ff59cbad0d7edacd6f103650e8da3933389f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "b98ca2cda24f5513194d78d8a6c011bad6088ce1ba7f9e52ce7aa16ac9783b53"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "a5b6e4b4c6333332fbb108463245c9cc89f7f253"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "9fa22e5ba6a25b780a66c3f9633de1a3a75f4316cf6c737e1e64e1a10c6b7f28"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "623beaf55da6883fe957f355836579dd8b07ce31"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a67febd3d6261fcb99504ae10ef33d05d6fdabe73750325cd2873f76801aece3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.i686-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "331a422404493e155ec9856cf500b61a63c8598d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "802df3b050033e3c813c8c98f502a1c02cdaf49bddd7353525bd8337a1090b3a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "3f4becd7866bd837eab2445756ce99e8ef5b946e"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "ce0c3e20ed821e37b44713c99b8b05d8c8dae315d693320af61d1dd21c3a1f3b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "57ce2bae7fedf165025f358af87645bfe3792745"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "0bb928384b2d3ebb9d23b09b0a0ecbcc7bc349316666dd4e9adac42ded632d2e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "aebc0fc377a2e9083ce4a2d815ed951d64919705"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "49684973e82f3843551955d1f4fbc594f9ab45583fbda4ea5ecaf391b295b25b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "e0bd15ad968e67eb9d34ea52f2f4ba622d9ae06f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "919fb380279d9b19e40dea71a91c2ce7d5decf8f2a29f43d61b01a7fc9781b13"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "8db8924d9e9543eab9d5c7b8d0d628d18641c2d7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c5f1f3bf9aac0851968d5efd1bd745ced6f0445f3007d209d3f8d917cdda735c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "407294eff3a423e6c9e524971ebf07574f5b827e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7d8a5ed577c7b71a991fbfef0dcd7c7eac051db0202c6d2998cacf6d2cc302f5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "f64667bd61f1f30ea247b10805ad15aad1a0d93c"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "5f3fe5774ded73475c2810e54a6fc0336e771702953d1a5c2816cd9341e4d78b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "26d4be5f96da9da90c78d02643671cc8e5e9fc80"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "510274aa559ef97a0d5c3ad297740515551cc12704da5c281fbe4abc1877c701"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d7373e82389d29c5a95dcdd4f6b8357749657893"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "0de57d86e757c0f5fb2ed7ab7e64f2696b1fe8a634096ed5ae3983d51902bd25"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "afceb55ddaf2f5b3e653763cea0a3b040baece32"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "00327b0d42cefe6b8542935345847b490e36a67540115b4884a3503c5a2ee394"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "939980b7627dbbf2c9ca8051bfdfcd038ffdc69d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "23668469fa4147f2593d3e9292ef9fcc2b4665636589afbc0d432bdc4d47818e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "1a3d0d4ff8ccaade68244fa448854e1be6f2f387"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "9f3dbd514f7d69f0fd6bfd57d8826180b2ffa6b55a154269cd5dd6e9dc2828fb"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "6667d634b42c008268d2efaf5d8b82bec0234f85"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "97a2da6f41e0d3d8e6ca1249003e1ba197b260682b6e36c72fbc0a6fbe975884"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d16bb7f8db78b65e9511e6dac533ba019fc14b30"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "530eddcb3f8a10438776283a061514b2d097540dc91e93d7631542c716c68fea"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "12c907c14bf7157135ec35d2f5235beaf2def9aa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ec896e3a1a3c6139b7f329fd98909fb8d59dab608541526b1b9e6dc73195a025"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "15f81d8cabb696625334ad6bd6c8f3ed38a31ea2"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "55409158b14a1893face17639bd0eecf46ca6db05234b929d54c8e4423881f2e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "914e15dc9b51458ed0164798bda63ad80836d360"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "215c317b59f343a4326ae279c1e4f1baa37652cdef7c6fc4a7687600ca514e63"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "81bbda0d2be325ff56429bf22b1d1293e4fb3a85"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "f2a2685f09f987512e460dfb48bccc1a47b8837642f6d55a52448c1fada61f20"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d810f3d00f904363eb7c2dc9f4daabc83ea98525"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "a6e9bdf3519f2800e0f730243ee44b39a1dc00b5003f55ba1d9d2f2e514ca509"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "63e108b19353fc20deb0f69b6c5a091d13ae6bb5"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "3d4da86a0a54f0d6965ee242f4d1c03065d71296f42ef77026b7cb1e01971f6d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "f39e5d021c7075d5329a6f9bbef347e6e6fedbe4"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "f490914d3bc37b215b39cf0234d99862a48b1c5017a7ea6fe67a12eb5410f9a0"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+1/Arpack.v3.8.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
