[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "67f4fb7593c3b191952973705562d20bdb68dd95"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "d8728038dbdf244ed711051c924794c735a48150ac4e6164a0095e8e827e5aae"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "6a625f65e2aea150f1c067b61a5270e612960f61"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0d2617e3d309b643b5a66cbaf785684e1d657f6d4970f2af479ea3baa28e6d49"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "489aa543648c8ee44e41c4f610bc415ac01e9e94"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c24f5d15aab33e4476ba3048b493ca66c1b0ca7ad847bfeb4888de85d103b32c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "5be20130e071a12fa9b994c905c0c848d21af856"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "74c08d97454ff1fd530a2dbd0bd17641d54b6c4072cd52650e7314d24d2a44ff"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "ede3770efb8ef37cc8d0673be03bb8d7457234ae"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "bd4342718ce1c8170a1a816875eabd0331c43a70efca05bdb64fbc3dfeebf143"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "a4f2a29a6eace6b20f59b37d8e6d0dbbc7c10921"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ecd9f7cf5e5fd2d96118747122956e77e9b2faaebbd1a909ed392db6eade270d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "b060793aae9b4b2deee5b8a64652ea029fd75fa3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "baaff5f23c846f5d205c16a7fa3499c70547fa6b5dcb2aee3f7f57ee9e951fb0"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f48887cea9185c257703794521536d8ce0a0e6de"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "59530f09b2dada7b0c6ae09c9c5271497111c7bbe248b9c4f861ec7bb953c754"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2954d918434af3fbf68c9146062f62191943e625"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ee9acb0a8386032050979de9f6e2630133aad641db8fec6190c1d1221e7966e0"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "055ae768229676dddb5a49cc58a63a58a7e0305a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "9cee1a2bc80ca336f16d3578b6243a8fc71dff75d544b17068740426cf3270d6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4fde67c2fd60b232e04576fcb0955cdab0a091b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "27a0afb395cf35361d05f493c6fe0b7226e9e05a04960e21ec352a2e7730d215"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dfeb65c34ffc95e67a13ff125c3ef2a5d9292cfa"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "6642cbe2d42dd5c47d5936dbeb09e9e81d3b398146102253f967a2f0e910c020"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85dc9aee538c44c234a19ad15a8a110064f336fe"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7541f986e6deeec26e3003390fa2144ac93a063d3fd843f098050628f94b1b28"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a21363c1f52ac7ac90a5605c2c65f78f6f5880a6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "df576e0cc70a5686976d66c6e59c7def4a1081be2f234566de046e3bd2d74f32"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5708090cafbbe39dcc36455ec64edd43825f4ce4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "5d49bcc65bb16f916c426c0da342f40510e53bbc6077235be83d5cf95bcec752"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "912ff75b95fd48c58119d62373fe341ea8201040"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "891983053974d321509c2a37820fd4c38cf0d8ed0c7ab3d1d79319863b001a4c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a9ed189572e2b86662f6f75b671524d5e2b48ab2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7d83123a06cfb7222fd6d63421c13f10203b11fc1e8abbd937560e9085b2cfad"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bbcc58331e0ca25cb9b156ee9f2022dcc3fdc914"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8272f979ecaf3dcd61ba4864260e8de61320a3d9eb8c842ba4ae1f1a4401de5e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "927de63423b8d08f6a6f6882b3c783d9dad02b25"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "46708e52c40eb66d1768dd9015c450b75c32f8b8e50b023cec60f28a17f53506"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "dbf4ff43a53c38ed3abe416f6f1e264bf9a61864"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0f8d43532362f0723588b31ba3ee1e9ce12bbc491b734850928ac8d700ffe1ad"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "463435a74efd032d3a926b8c636d6f27dbfcdccd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "bf3e707d9bc9563aea4622f24f4adbfd2c95167f9861c611a06672e16cb758bf"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "20c1a3f02d7eecd7d0931246dc7ed1eed0701b45"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "729f61c3b191bccb4ea450b2b0fa73748457c2afc137bcaf6bd1a427ce0debca"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "280eb289a01a38a8d93178adf869e9a717c9b17e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8c9deb0abab8307c7ddafbe170e07c7c6ad123b75bc24c60185862659486e084"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "10d863f8760cfa962052a33b10ea888febac6a63"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "cbf8e1e648372674c69b79c5b15371d6ecce50e55b174ae621a34ab1b2d5c19d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.i686-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "102793a2e3a15eca008e47962be9fb699cb24393"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "9aedfcac730a3a9a227d88170002740a561800ad4c936c61c560954337aabc36"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "5c3f94d9712ca49416bbf765f30110ee45229190"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "853bd0234627685d07153c7d1a899a87fb6ddb5257766b5715bcf1fa73a99633"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "646fc7274b471a633d3df51cd62d230a48c606c6"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "0755645a400700afbd8468ecc7203a06e5758daae12efd230c3dfbb7df463da1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "676773c9265b8f683567a9b4c0ec96ca8985ba59"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "d12927c07d9e8d7350f07851dd9fca7f196493e298183bd79f77ba9d4e19a58f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "4587c8b7ac97f7ef099acf5fc523fe28842296ee"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8a619ff5563fc5ab4877bc63e186eda446e3c776683d4018753875bd4d3e0439"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "0f0d1e0d95825a47ce0a3653aae7dca13541b18b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "d2fba1fbe2669fe0a26560025483bd98dcb6d58ab98a48f06cbeee6a7977a4c7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "7a8041b91e15f10e448c1be8c45391dd209ca700"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "095b880abe2d20a06293022edc5382493603384c315dc6799ce22c34b01b5cf9"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "3be85d8f2d66c9c8980af7f88b87f2fe49c0fabd"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "cd4cea87f15ee41b61264a5d4c562cf7edf2eed4b9333cf7321f40a288cef6f6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "e2b99fe59a1259367f17a21e76e9b45e4a0a3499"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "a8524f770297c1dd1871d6466a2c2c2dc29a578d9387eeaf04ba13d4fd20d4b4"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "ce635306e33033aa921e19a95d36e3a8ef7879a3"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "7f21f892ff59ac65c72b5ec8b805a97088c78efff96aa219f5e316a3fbce1bee"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "525f04db837151bd25b00d94caa02183052be62d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "435e2e496e3815f320f186adff246e33689f8d93a068bb4fae823fb32f5b6dd6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "7d8c5a67c6d756e6db8aeeb2915bd986288b7a73"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a5959354ac478d129c277e7d5d53b5a5e98150c793e1123c7918634e1ea0f93c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "08e5c4f33a324282e9fe0f9afad415632d55adce"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "3423aa8fae5c43bbfdac52df795e7158eaf18024822b9ef39459c99d9935747f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "0ec058f91d6c5ca9965f7bfec220442f28168ea7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ed734a23caf2557fbe26481875d4d3a9f1a21d68d0eecac06b07618446c40586"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "95c7755808b7f86ab12f495210e0dfa55fc62709"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0f3c588837ea379cd2f618092f4e101c52688e172d40639124bc9c372751e46e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "4da431fc7e7ca3d7c57847f9cdb16b76bec39c38"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "9d89eb0818672771940eafa57df182c7de3b4434d3740ecd51454bee4eb5e25f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "a61d09e1b5ba23e3458b8b6eaa0883fc7951a632"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "c7383a41268742930160af9d556e1a6696e8df41196f39129dd83bf28d760172"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "9f6d9069237529d7348d9fbd8250fc4a88f545b3"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "b7420055e4492f451f4bc498d5ea4ed35aa89ef1c738a22e3ab8e6a4ba95afab"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "25a332201f5b1b469ad5e4ef6c7de33674040520"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "663451e043b353129d4dc3fc2af73e4c037f7f9d7f8d009b15170d84ae26d4ec"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "24f18fc29b845e2c5a19ba1aa55dc2c3aef8e5a1"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "d4a6f403aa3375402b1b06820e3d7a81e4c7682ec92705d6d9fe48c77f45396d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "748349dd2d86fb85b14dc7e213abf0741d0e7ea0"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "136ba1e7d7267a3f7d0053a3071f44a3923c654aeb81441ad1510fc5c95cf7dd"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "8430205dc400a90453c7df7fc6a17cc8616960e2"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "b177981b4b0b8f0dcd1bf73162d0d6c70a33d4400386bc946d5c68e6d48352f7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.7.0+1/Arpack.v3.7.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
