[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "f65e5629634d1818dee6024ff20b288adfc19e08"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "90124dc679004c401e15a0de7f2d5cab7306e55790e18688598861ebb34ec456"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "aa2381c42de95baa561946270033207d42e0e2e1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ff092444075dfa40edbf145dcb4ff637cfcbb345dfbc01d1800614a6151fe5be"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "c19d35a9b9725b1d3bb57456c9a1b205610f7a51"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f4ebc896819df5e12dbe626dc2c51e404ee58ff4c71b6cf133c34a6b3c2c5446"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "9b56f9bb198cdd3ec5015b0b5296eed354b23b74"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a957491e0bd1e48f75b04e850eb31c3d2e04b532241b24f67fe12e0ce99fff3b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "b508805c1fa436ff9705ca090aac6d73b81ee951"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8fbaf1b9e2f1c2a652e35b1c9eb3abdc75c51699e7a7170e4c369dc1f35f1357"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "af4dd32797b3ce161a5266d60f27c7952bb2b0a7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "6cf03f6c7ac7e483213b3712f874c56f710eade1e1708fe1c6d76cf6e36a524f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "507aaa85781da17d2d785e53e3e276efb9ab4332"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "2ef3114d4109ac8ce0faf6ee9cb76725c8fae5b87c700a219d861e478e03412a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c2465259a7c4a3d6ad86701fd4879fd9b7f2bb6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "5943784ae66dd7a0c600e7154ace6cd146a45202775aaccc706ab9f9d2e92688"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4e7d14de4f6745464012fc788100ad6ab03ef66"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "6936ca7383dcffac0454fd542b6e0a409215148782e0dbbd7d90ddc7bec0b53f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b33850dd9b1c3a3ec52974244cbd99e756d62fcc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "fa3d9de9c2507d0b972bb3d652a4c6a7327be226c4377fcbda218ab4609eb077"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b2ccc65162d3b9d2e7e10e7f9b54fd179dcef24d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7cf5144bca11cc4e2b145e5307aeabc4a7e398931fedb2b4e52fa32b82defee7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "27b1d51c3aa6f456fcd3e3dd7159b7b810ec09fb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "dfbddc4f98054ed19dc77a499192eb8402c4f65aa16ce3bb11bb0b50b384e01e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e2034ff6da11bb8ff058777dbce68deca8cc6ef1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "dae4313a0f509f3942c1178646bef809d4e934e51b2e7dceb8668b881f9ae650"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "63b189dd5f6b2402de9ce35b29db69cf5e3d2b31"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "73b2fe3f8836239c17d45d8316d3dbf16b7bd14d7949a214461b40f993691a7f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e1a8703f7c00473e54a533ec3c65e660948298e8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e4890f41ef9f368a654c642e0cc7017a8514f0b52bec39ec4652021f30421d65"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6fc5faa22ddfc04daf5cc2aa72993b35eee91b0a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "824b4c0a18f5fe859ddeb12b18a044bf83acefc005dcf503c16f4fb21356e6e5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e9f99dc98bf4a1f5a44abf2d7db7fb339b2290b2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "dd6e9a205a64858d6afba5c678efc09786eaac77d23bc325d26e1bffdb16c889"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a7c53128b99e560feac9c9677f2efad357bbc6ee"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7d2b1ed0fa07ca5752970742c6c4004d8011ffdffc9997d5085adc7c11f24053"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "be98c0ce5d32797c899158efb9376e7e073d885c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "fc675ced4140f1943f5d1a94a6f7ec168f0809a264f0520bbd8b8cd54c788576"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "fe7836326de0fa7a4089410c0dd271588e5651ec"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "840791a4375156a40cc0f822e54abb223568cad9c18ef87c9db23396ac438289"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "a5099d1178e58a8e9384ab2c94c14c09ccac3726"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ed12a2aaccb5bb0847de277fe01f1be0d510c08d46e4a3c9cf18e0f357c7c2a0"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "d808437e805495f58edb7119d6a48b253ab1a10e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "83e78976debe1a6b7f5924025271d27088e6c52349358ebe189104b0a23a1b3b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "52ce6fe02630a6670dadf114a3af329234337501"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f790c5b08113f582c8bbeba55069cf0c66f62adc0650f5d1d1cd5d80827b0d1e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "32b8687212a1267425454b3831844e3f987d893c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0d66855d43bfae9bb09b8401f747283881cac7565d0a6f63e751f629767f9727"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.i686-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "775b9eb176a7f67bc9b4f765fb7128c21b84aeb2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7c8c224a6c3c43dbb1ade1688ba84721a7cdc4b812ab7b7ba04de77a28094932"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "917c05b70b3e5f42f571b900dbceef3ffd4b1f2b"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "88c78c1a8bbbaf24e58fc95047423f5a2e2de0ec46a0d447749548b93a3181ff"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "c9e3e18a40153e26d80a3327429b93321351ecee"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "2ab860cc3fc7aac96131ec6257b657dc99122ec001fe4a382deb994f1a207bee"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "a908ea06647a6f408d9f56db1397155f0dea9e5c"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "603f1ae2f9d97d7c4d3c20af58e625e477e8c3be13334def85ba9c357d47f0d2"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "d189b4f54fcbc3c412cbc40c8ddc6b58da82061d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "bf4f0fc75ff3a0d9c2c89c1ea0b2e261c18268cbf832f7a6c1ca30950b8ad092"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "41189378832f2fe56956c95b0d0c368de5adeb18"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e1881de5c8b2198510c50c14ca0badd37c3e508b49e241f3da63037483708669"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "27c32c092fd828f7c68e592781be433bf255a6e9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f08326e08a027d5df42cd01e7b361089c99d97d8a2594b5e0b8e469d52dd566d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "45a4f7b0a662837493d199d5d931bf2293af9d3f"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "0414b660d35606b96333b45762705b3e8708055067cad89775aa474b8282747d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "0ceb78e06c75ac0e120d00d40dad4647601883de"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "8865ba22ac8a76519a8798d4e43219de58129836a6302a706602d9937c271a6f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "8707bf214d5c2e22e469e5fdba9ee51d830ce8ba"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "04e1d024f036d8b544c4cc1fcd5afa0041ddaa20ddc1195708f2754d55302b7f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "75862e9c9374c3d23a8eeda7c4014c36ba434761"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "b717ef8135a9a8b7574dffbff02a738852c649c30a8838c87caeb0dbc0628b23"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "61013d5ec1ffcf4393251ce40b781f4067acf2b3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a7760874d8640893de045a5e6027f198da7b8076250265c23f7c261ae5e0f959"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "cdf6dc8aa6771a61c6c65a5a5c1a8d1b75f50a2f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "bd9a06393abd0551e96d4bd92fee9968e56352caab686c346dfed600bb73ce1e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "f783143488f835e5e6af22f32cb087d00a2d132a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "84d5c49663821af702c9963b877c6a8d0c7d6011fb0689c2650fc5bb11541702"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "ef998040eee7be23dbca003605911b08069abd8a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "d8da17eeb02ab17ecaf7adcc1a0a264f645a8cd863daec905ee92469d88143bb"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "3cbd980c8aa7e469bb14c86df73f47ef1f0af05f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "53c6af1dbdf4c8ad175679874027b7576f26790bb0094919138b6f4347b80b68"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "a9695de98c8d823657f09d47a40299c04be525b2"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "f0ec22a68c01c288c0cf9f08758bde25cee158a69076a884a249d636af546446"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "7a4221950fdf67191a1de5c6af3a2be428ef4d34"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "2b9dbbaa0ecb3cc5671a1dbfb8dbe9daba7161e70237e63ee667e3d0d3a19a7d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "340497cbc58e4e0782e50888ea5dcd5e2e12f6b9"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "f17029b0e355f720f5dfcd04ad34ed6a931b86c82cf4d4d89a297a1b05eaa9ad"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "278ce838a9a2a1e512f72bfaf58882b97411867e"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "7eb2ebf7b36307530b71065d56550be59bef189b17c2a9b6d7446e07942d921e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "4267ad6abe43bb2251e74ed5adebf5274224ddd6"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "7e9ec065795402c04f168789ac7327ebed40807760440d99baf106fcd49cd926"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "e667e2c9c96d35ad7fb90fd23042e46ab3f375bf"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "b8dbb41d072f25683d3ac7c7e9e3e7e1d444d719f00df6be97b7ba1e334c0b1d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+1/Arpack.v3.5.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
