[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "5afea61a69d0edb8644dd297c3d1dd5a49da2ad3"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "3ab0e1dc5e653b6fd4d5d65c509b0dbb3e71ecf51eaa8ed7e888d91e13c26d0f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "3967d7d08151db92dd9b6825edd8ba06dec56e10"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "2418eaaa4740d17e314561addbd8975875deb2f922e1fc28c8d8419790520bea"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "68ee08a4d43540048540eefe5d34d648f1f1b3b1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4a08112b9e55402e0e35e3b3a0922b196cfc6aeb8458b7bc5621ddd7d1e10e1e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "9b0f9dd1db4dcd5e0594a46f27cd8440ab4855c6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "1548c7131b8b06a67c72b271c08dffd3b322287d8f2a6c8a41c48649b62e1101"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "7d8d976cd13cc5ad4391fe815dacca2bd869a957"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "dbf4980137f0f793804fd9cb2529c6ca6ad01a556b98215507ae7e06d53a153f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "b1f3349786f29a3538fe1c05b98e5cd3f9800e45"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "92193a77236b641a94aa0f6963d651be28eddb63b38ab2772d851d02827d51e6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "99945681738ad0a62d2292490a43dcde241547d0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0525b1dcc7e79039d3c3e43b4342ae7725361d2e07da83f066fae43dce98e7d3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "8695ffc0e91b45ca90753eed28d01e69f9b0f39d"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "36e732ef06aacac9130cb0bf47e3dfa30ba6d9f7f53361fe4f1b5634edec0e1f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "7ab338c383486aae40c69d489e79ed506aa1a9d4"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "a44d0d3773a0caa04fb112bada11b8dc878b2410af0da47533e1d2d07f877a09"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4dcfb7136c0f092cf2deb3c90f8cfbbed8eac8d0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8015d339e9b3c3a7b73675b8c100380997de72f9177295fcf44d70b477bab5ea"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c29121a7510d7729ac08c3abc0cd4581b03c99a1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "1c0f7677f4841ad797bf1d55bfaedd8fd88dd64e67f72271d8b58d0dc73d7c1a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "659fb03643e7ae72898cbd4dab5f071ceb7b5391"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e4a634a1b023819337f0b9bc1e129b01d1fd7c03a07ccca72e07c2de0579ddca"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "78ab62e03033f5356ef3e1908c83710709471fc2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "058f958dee615b8ef6da73b68a7d2a5269f7c92bb69eda33b31beaccb3a4efe8"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ae93ce8f03663dfc9c7848ba0cbdf6dcdd02f7f6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "6c799332ca195a5ebae301feb8b755cb2c419ee1b8235f82d41585440155b5af"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4442c0e2954bba6456a1021ba9bf4f4b53d3b4f9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f11ff6c947e91a1a8ab97badab2692a4d0f3f3eb8d0ec446cc496682259a291a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6f925cfc47632f833d5636489b03f5c8d348a369"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c1fadf72a7d8838a946dc6d2c767f6ff29c671cbbdae4d24539ad9851f02d72b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fa06b17ccd974e2c0811dafdd8f13c95bfb689b7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "60001ca2b50ba6a409db7e68dc140777876321c06fe7281f7df26c5d04d1d9b1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab82ebaef547e59be4541632e97c18c92c12162b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "19def373af5cb645350d8d0c97c037f5397a8bfc3de05ada58f4959ec834c31a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "49b07ab99ab04faa3600f2cb0a5431f62f6030a1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c322bf93163cce41aacfe3165d3cccebaa39cb40c6e46e63c7abd83299bcd62d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a043dda77b9ee71443e4e38c37cb25aa38454327"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0ada87e53f65739e82dc372adb7a681dfe5c2ed6426d7d8e8a2d9734e1157245"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bfcac99dd1b5c89d35328b37a7094d43d0f01fa3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "304ea939d49cbf0a14f3a2e339dc2e18090d16c7fb438d90b4c0245b127bfb42"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "ca490e92c7edddbc7f35352fb441d566749b6e0a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "1270d94969a561d5672596635d61fc526a9524e82acf116c70d553c737405ebf"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "3a056baa7fd79438687b3d0d199bef5f85e59842"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "23ae57c87b469480f82ceb01b6f6f5047beee9d2a56fdf466a2835f0a54c0d42"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "ca34b2e4878493acdfee3247e95692462d32fa73"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "672faa4bf607097c2a5040e71e8946aa378ba1b4545b0746b773c5bce0d67f06"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "059779bbc510fdd9d800fcb5d44eb9e657652a2b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7774ce1ebe69c9beee7a8314a21da574d37fa34430f203906f412fcf2c4b5eb1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "e2bd5f973deeb9d0d5df5bc93836495accdb2459"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "fd34f54b5998861fc4b1e65fe83af7429cf7f124965418b831b05492e8d8876b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.i686-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "37cdb810917c40c890338f371126bba5e2302b8b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "933f5b35f9159ecf56d8aa84699086acaa90d20cb7f001e7d53e3d10ab093e53"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "5ab9307673058f00d258b5512884c793e37eb068"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "2aca61af894a621312e308eb2bcddfa617671318d16faec1c13189d6d6130b8d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "8c4f88da0cc2346ae5172e326c05049b72135fdb"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "97c61aff1be47c6c2a534dc02978b1e5b62da33e89ce4dfa0b7e99dc13eb419b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "5838c433f356e59292b5e2cfb3c86c0aac290be8"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "c073e0951f428d54ffac1be0e6a1ee88d6c7dcd6ce4a8147110cc4f63a8d2af5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "87d5f8f175d3ce1c539495729931d6eee208d4ab"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "1f9c5f14e9a8bd6156f7ada5089c3ef048cebc8afb4dc420e3684af1d9069f3f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "444f7a2d9319dc1aef1ac12fcfbb76bb80597990"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "fd0decd94b1533c28e652d47a8064e3be081528052c12cebc5e3e7d281801507"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "c344091d0129ff3d0b54b1d86e2c7da182b2ec25"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "3d200d4143b38ccc4ca9086d0b88bde5fd10a0ddce623efbd12cd39284e0e544"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "6a2fc1530054918f3d039a5bd177154b71c29715"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "4076d3556daf0ef297c3d7b8da53ee9e924851bf4b68084e886585d61d4b4e10"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "801ff2905064feccb869f5b58843b9a82a385dfc"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "4369d0901f639b5774643acfbe1440aecc50d0f789599d38f27951c349c2c652"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d1ae5dd0cbcb4e69c493112eee5a5c5d7c817569"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "d3b2d7a372ce9da2bd5e7083b372118a1db50a4a8c4929cd16e664eb6f98d17a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "565aeeebe118f3967f55ff098041d7506f0ecaef"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "6cb1a28e3e6040e466aa8c05e0cb5e2d975ddf3bade1b1de3ee55633a756d2f6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "9e0d2181fb07772d0b6520eb7fd84ee70e866737"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "bfd4dc410db2b789c1f24f5bc7db3e3cfbbc68cb3c6b8288eb349e959c74ecd3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "a5e246fd27c37dc4f30589ffbba3bdcd09ffc8d2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e9c73911b2a458d3e84755871c8eef18e5c86ae66821e81dd47a786e436cd3b0"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "f166e03b2df2811b6d8aa2e249852be6ca78adf7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "514a66b4b70dd0a06e6c660ef23d966e74bd77c2e222431ebf1438daf4bccc77"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "90f740d11ff7942cd554df3e209ceb01aebdcb8c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "26456dd2a3ad4d284ccdb50afd14c4a27439ad8b1820c1c9313972ce3770e3f3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "5fe1e64c00622c2784d19ac9a459bae569df2cfc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "bac383e1af089cab68ffbb315dc4b5a385b9a9aeb4acfadf338fc716c586b66a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "f5dba5f546239c3c0ec90761491630db1fb7171e"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "a9694bf476b5d062b088fa6075593ac3ea95455a9f6065bb7e2f60101c0e9a3a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "6cc61c6de0c6f1c2f40bafb25dd86278c8fc0fe3"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "abf339083329855725a664d5801d4d0cc43d39c54f0e8317aafd020f9b9bd9f3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "59cfb759178d65b45ffed95f23748b78d708922c"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "1c8d99a29d21d85676ac39cec0a109a8a2dc929fe2c1489ebc64a4c4ee8fe507"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "6970b52d9738f61f02946745b1cbecce469999a9"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "eff9dab0ecd0d6af715e26a01da927bb8d403137a42e8bfefc7779eaf621dc28"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "29efad2336fa56f0c04adba6ee03b11902160298"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "b907758fd362822bef54bef975d7217ccac951a61e51a192b302313c52009a6f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "423e53980c9061bc2dc45604610642430f7bdc38"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "dfe5b4d6cd53545466c311b68caf6823cff4a84ee4ac84e2729a26570c26a155"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+2/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
