[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "3c71ab14d95125828fa45e5b406ec56e6c16154e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ad0a811aa12642bcb76504c1cd673310519548ea64d52190b93c11688c9b19f6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "fa0df2a21365ef3c9b609bd4333ddb6b1a07319d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "118683285effc3f6c2b9497be2a390d4f175abe010b74e62c956eab572ab7c0d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "8e542fd335317f773b0fe7599510d7982dd0b392"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "759e4684ddc3a7f89101ce7f2625d415f0da56809c4db0ebfd1ee05c2df743c4"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "4ef845664fb4c69b6758016ff168048a5c658b64"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "544c42001cb6401f19387ba6e350eb06187ba686bd19241b4167952a9b56dac2"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "bb8a6fee58c87575abf14b827faf3061388f2622"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "778dc07364725c846d3871dab790b43b6d74c62cf6c52b10632dd5babe83aa88"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "f2d9ce9f2d105147c0a842d6737549b287919a6d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "49d1a1687b2268d632296824a3205f0636f80f4b7df253fd2a3130b5bb897de4"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f29eb1dcc5ba43fb372af86287d81b758fc886e4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f449423a867447e81fe837c5d34ef0ef5ec2a17a0a7950b32bb98ef3a62a0de3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "625b5e4b0c9fa91454b27d2b38bc71ed9d4ae782"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f1a1a4862d88571adacf9eb124ba20b88e7ddeb7ec96564cbe912300215f246a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "342fd881351cc30e59a629fbe03afb667b7ec4f2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "806acfee4835172ab232ab8b83f5bfdca57d114f31af498d141f043f01aa0dff"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4787d9edcf103e105a2c49aba80385f4ce73b711"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "71e519001dbb9bd861365dc3b5c154171206f2e80826d430039fde13110aa2e7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8ccc42d42cbde3d05489b43764da817ff22f7c41"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8840c94bd27deb9379bd2de0ed4df3ef7e778c2611b543f1ad2686c3295296a1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd15eb505f378366694ea2bfc854baaac5bd8f1a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7f73a4432745a892f579c4a80c7c6f4e2f64e81347d6e379a481fc9e018efa01"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "5f3204cce40cc88d4b1e0dae6372758d5a76eb54"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "142b7146acbf0972f891e04a8ff5f503d877c3d4170779d9ff6900773cc8dfed"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "e40f8890eaae8c25d9e977b7770e18e999ff2ee5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ec5efb2d9e87b78da882b3450ebdcb42d68221295424d24713bc981fbc2ad612"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "32ceca12a507bbe3c9124871c1fbf4e765ab8fc3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "2881655bf7ba4ee58d569182898c4404a23ed04e61cc8a39c78bddb53005e3fd"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "7593f592d8fe755ddd62812494b6c5aa5eb5a01c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8ef4a7a49a4731e26c7cc56303b354c46673b22127ab7708d97c374d58bac1a3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "75cd0976b8fb8af3c9e46452d271a55a76013898"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "5fdcd05484cb24ddfe4fdf95e656d21d21d43951ff645b5a94a47acf99c3688b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.i686-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "0481d64dfe8979fff64d1f0e3a5731fa3fbad017"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "602f75f1aa82e0e5f926f7345d7f17a198b78828fbc97ad5c733100899e384c1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "d92657f9e98b69ba9523d6dbd48aeb657a8d2184"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "ae5cc2b12d00d944fecbf6ea3cbb4eb4d719db3fd709dff203453e6cfc2fad2d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "44f50f478c5a305c4efe5a68994154b07edb9256"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "a37e8be24dd3d60699c22f839d58b25c104b84b11214410fa9eb6e4449b38858"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "2909ce82c0047de392a11f25b8f49080e5184678"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "f074a64cc30c1619b23efd11c657ec16d3e35f8b60e8affb37c7fbc5f5f0b248"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "4b5fb70628c1cdc10f3a9740c5b14593cb8749fa"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "39337036a396800867400a22e8b56dff98ca8b9c35d4cb6fb9976f2003d0b6a2"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "f17d76668a2ca07ff54fedfd5a138f47c05a1d1a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "97b7c1033f8fad92cd63943b3a82d497e9e6d0c68bc9a153e6cb5a0f2ff58a62"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "075ff7c750bc8b849c715c85ae9ee7ceb6cc08d0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "84d19c292772c6694d75887f451ce84f0c3d60f3ed80179bfcddf362529fa671"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d8cc22aa76410413b427e42747347417681079d9"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "ae7e46e8151a3d981ea0420c31920174c242f85fa87508685363ce9cd3ce8ad2"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "e1631d3aec690feb8f2330c629e853190df49fbe"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "3f1b0fa8ba2f317782f8775b7773e0120659ea022e3aab5f089c2542ef154cec"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "8b226c93b96a20b28797726c6c3ed579d94a7390"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "dab59d338ad086de2b6bea92440be9d47ec4a2d887163d3c8a586fcff8508199"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "2326c193a0f66ee86c5438acc2e471db63e379d0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "50723f057de66e7f88aab53db0c589da41c6a39ff64bf3cbb3724e89d50b4746"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "3c4fcc68d79c91e22721d26d6c3e978246118e67"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0a2dc204f12c076b037ac979426cf73354a12429161aad507635155aa37be605"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "a3574b856d42e43726c84b96265e4398742e9c70"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a9f71cbfa28a7289588a04a41dc558f0760c72e809905a7212b35143b0a30c1a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "cf92d44d2add097102ba8d7d62e8046585209d5c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "5944abfbbdb4a303b4191720135944072a59155c44726257913a2383da11c964"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "6d36b5d39471f12d695ddd46867d6b31ae357149"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ccdc22864984015cc8de964b55b7ae8813555de3b333f913b13cc409c43bba39"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "cf821fc41689650502de6b63bb2bcc96cd39e063"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "98769089e16da2282f189785f4497d1b48a297e380da97f0090e46459ec95857"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "03cc8df1b45df5d5558a7d9d66bf786963284810"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "0c367a29835ac0c8cc54d44a89d525f9104e00289cb5e8b04cba88d26950a48a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "b44a2e6c8478f56d9e07ef5c7f89feb9c9558332"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "1d34e7f761e452efe9643ac7caafa94f00ffed2a6eab85863763afa8a0183d92"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d63795ba2ddd1306abe68da4d8062a5e93d1b034"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "93b6c10928ba2fe1e3ab7502350c2cbd1775062a9a89ba658ec5e52765671b3b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "fd757b4bdb57725be12d693a6a8481137b5cc5df"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "3de9504bf8444dfc2277d6db00f6d9fe905f984e984c72ab64f0e9c59641c5a4"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "1505a74288b7bdab45c9a89acd05f1273f322c31"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "58f869d5b8f64b2b500fce72aaa2e16154de25cc9f75eb7543b47788ae5ab46e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d08da19c1549f66e6a4b4af5008efd57cfca59fe"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "d42b0b882ea08beb3a690fcabb0865cf79ee1de62246df93b5740e46198ec80b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.8.0+0/Arpack.v3.8.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
