[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "003f7421aae7536c855b10f9e13414f6bc418df1"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "f820f1893bebfb5f2216ca0131110b005884fc713c10504dd53f005c1e03bd06"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "7b629db4f69d3d82264006f448d146fef7a2c2e2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "673939058cd89d405067e30a6caad09ff695784fe36c27651c2ed838de62d7ea"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "75186b6766d0c91b6aee4528e099b9c8103c1691"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ac3ca3e253ba410abfdf9c80f4912f45c8919a7a995a37faf141e016d16a81c7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "02b07b55045d077695d95f890d51519a8ad5757e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "b2077e91081396ce66f8fb545cf9e60e160c93482850e7e66bd4928a5e647ec7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "533d88eaa55631022d9446de9fac76e5d15c5da6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4c400a0581e5ef334a43b22665f6435c282cbeacb72c6edb782558cdbb0d6ddc"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "acda086c27475b895f8f5e1371f1916517484ce4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "5692bab53f10f84c4a3c75516c39955ca9c75a0a1dbaae56fb93d9a9988b4f9c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "431051453c784468240abe6d8374e47dc298e940"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "83c0e7b0a8cd502753638f44c4127175c3d6e1f0d59a35bf5af7fcb3efa4f9d5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "28cf8075d7fe66a1035afc6c7dce845dd455fe8f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "227c75244292a26fc39f15d38a9a444c33e4e6d8feb19d18d60530f45ac6ab09"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "560390564dab6b22a90d29b2d43a5e17544c8b70"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8788409daaa3b21fa665b5c399d6db9db651bd55fb5499f525b12dc7f9ea248f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8f974808e92c05e8f6ec681e60aa023b0ad83092"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "53bda0c936355190fd645843283b931d58d0af155a7e7ee06970130de7f3413d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0007df4d485f785a92a00f7b0c2a2ca9a72cbc46"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "3fe92309e88590e3a5864bbe92cb6145ec20599d7360d69d7ad9ee6e6fc72853"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "92aa9b5726be71e231d360939298a20e6a39491d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "153b433de489b09eb4a4db11a7f43c5959854d6a77c619948cdbfe9ca1ce957c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "963a31bbc082fb5882e61fd074bb1a912d149a17"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ca19765acdd19445f8ca36d9b310423fee78065f85b7ec130b034886b741ad69"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "85852b6d02aaac3ecb496efff1db0b1842157f93"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f8d2f4b30b27ae0fe115c1a05f7b67c72072cb293be143fefb70f966d2880b4a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "34d51b57f0b1a158a88baf0cfa6a7767485c1b81"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a79479eedbbfd71c3047b1af837c46f2a45e9dfd82c38b28e85a77bddba79c2b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2f036c7a4665bb2dfdd251b034052be859bb79b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "53e3a8ba1be1a3c0339c5169523e2f0a3b3263f280a42ca0f2170ed4b1ebe6e4"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1bbc37ee79de51530137ded5d8051fd868b3afb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0ddcfca8922960c1b00c5f2ec26e36aa3410a2db07b887b6d98454203cfdf694"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "47354c954743744448134086d762dff233fbbeae"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8933e241fe70c224df9bb21c34416f45fbcd0432f773b7dee6a40d31260e0fab"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fa589ed1426a272031d3ef09488f7307000c69cf"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "9bf3bd1c07c896e1e7231f35156d5bca2065eba8c6f99c72f80f2e0b65e78c5d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "b70553369b158f42f8508c280599bd3d9c1dcfdd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "58b32c9174cb79806af53981ed974fefb56a8267e797e90274312104aaa55851"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "c38f8668839a182e7ea6973a41e5daba0360de0e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "22a7abf628ecdd7856c0f53197b66bd725e64185769492b4eebfe6e5cfaeb95c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "f60c30745096f9c6a00e251a2287127b51b5ae84"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a730c2ad038dc7d1d28f207494fb1dfcc66502af33532578e8f35257a18d9076"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "cdace6f00024fd12b6958f128933db202b8f86e1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7cf508e2ac781df7bed2ebd03e5fb66286f0d9c06f88539d98d964079c9e42cb"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "512a86b6ef4e890c8f174cbd28139c08785e71ce"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "1351e09419ca79d3c7007890ad9dd9b985ed97635b908aad1478a0f19bd574bb"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.i686-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "216a452624adfa640827578cf350fc51825885d9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a6f7eed9987a12aedb16d71ceaea4dc4be9436ee41fed90703091fe95b20ab07"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "8e520bcf1bb2980efa78b212e7a8776bba002d95"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "08b26d54f603da1c5066e51aaec0bf3987cf89a9173764c66c7bb6ef6d3c43f4"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "a64ad22fde043a813f31cd31e83f218b4bf781f9"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "725c8d1409a22c51ca820dc590b034ec578330b343a39eda4092157478df0a21"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "3462b28f6313bd97fb7c7b682a9e3c9936985ca1"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "d7ad16c3aa729e48a267413f042e3f9094d5bb303506a6efc7c5801afbecba97"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "2a326673c09137037e7eabc06ba8cf9282e0715c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "bf2f64f814c6a0eb28798032c4ce7c8bc54ef21635aa144e2ba55f7b4770205a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "d45e9b38f23009e532eca3dbc573a4bd48723fd3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "cedb912da389dc2e0c1656f1a0e21df926335a04846deea4eea1c5c199c479e6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "e5186e615859d7c39ef68fba908ba7b9efb205b4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "42bde44836d7a872b381fd01038654ed5622f276f7f88b207a1880b6565033eb"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "dece31bd948216d4d6cefe837f74d274a23232f1"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "a8295dbd8049e77057a70b78b4a372e6d3efb81fe7b9c938bcd3a756aefd666f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "abf9cbfd5c6ac161e2ec96f7ce06b8f0b95e37de"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "41c61bfed502afaeef222b7ddd9f0690e1bed8bf267f07e15e026ba8f566f571"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "ae03d9cd5e84d0fcb535170aacc840d51e117d4f"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "1e99664fae48661be8a2da3ceca4840ed7eaa86a09d17610c7da976ab291cbf7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "70aa926abae869c719c986e24f9344c7d150a248"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "6d70bca5353f959941d27035c86fe0631e601f3b113d6e16ffb2ef9f48b07617"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "e9057700278e191afaf74dfa4eaf9ba8af9b1324"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "2c315e45dafd922486929b8a4c2be56ab8756ca69d6fa2655972ed96bdf6818b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "e0760b09dcb9d6df8cbe44f1296156b431767314"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "d10d6eedef1ecbf4fd7b9032b857b35e489d7bfe3752e85e9017a36753a3ab98"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "abf4638f7e2394c455aec864ad77b0b6a0c94650"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "fe8153e6293e9ac78ca37160020f71952372262b1ea24a50b1216fe77fda4617"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "fa65aa0b4ae5d86bb362b11a9b05a80558f3c44f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0afc86430eeba055e268c52797432d95498947624dc23884d7feff83502083a7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "da5b6ce21317ab9eac7ddf7d7a2b5262915b08aa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "20b1e7da344bee29f0e6c06465dcb9274b75777f6b22886d0504844d1fd7bc53"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "b40c0bb44c09f2dfb5737081faf49f974e9dd506"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "80bac6dedf9c5f763678c9849eaa1f607110e1f2eddfa89b8e7c1da7cb427417"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "e2037b064ddac42017d9b262707f74b3b069b5eb"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "4c00fc8abcd4cd5d7ff7ad377db1f393faddd51c090afb3965779d9b5f25b96e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "0c3b5d075b7db8c0025cb6ad6467e38fa0f92457"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "d1d1a88bbc8b071cf5d96f1b1b37ff803a9d2379aaceed3a3f0baf3bbc0b8ae7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "d86e52d86270651ab654497fbd846797ac5776ad"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "ffd91bc7593c30e92f86740d99fdc5849b41e42cdd23628c3b9de314f524595f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "e8fbce476199fc94b815fb2cd6789e187854a792"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "5b081693fb9614331c0bb1b35265392c5641f5abdf15e10fbff923cf9de5b248"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "6ae932889158004665d70d29fe85c65a2c62945b"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "96245f54ae5e77eca9811d16c4a7734cc5cecf456267b57efc4a3059bb5c4de0"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+1/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
