[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "68ab23626f929fd00a7d580ef0f2dba09ff04686"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "6e6040da86be821315344759f0f4f73154d21fa29dd2397d1a54fa86f3bbdcbc"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "813486a4165a19074c0fcfd662e9abf9b0247aef"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "2bf6c33bf18b76787c37ddfd1e96f121e7612bdebcb0e369e2fe02e8320eda17"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "701b069a981c57c093c575f667ddd18a9b1353c6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "76435fd4682514309d5c61b16cef8cdb7b72b7a8dadc9a5caa1611f1b1cee2f8"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "9fec3a636f01b5489b31338f28602dd83ae633e9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "682e6cc072b8e629f9618416cfd3343cdfbd4d0c8ac62f3b274366fb421dc54f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "427a67a789cdfb822f7a2764d105d94e5084b9b0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "578bc319ab0a918dd1ac8065eaa747a77432dddecae31cf2bc66623f157a5422"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "6d285dd824afa59274cdd0c7d746a815e6ba8234"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a1ba05f76bd77e460530e0da41ef88360e055af625508991f1e9359ffe5586f4"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "cb1a2bdfac11de8899177723c2d9110da4401922"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a0d890886920ca38439161efe87b64e526f62a80c25a8910f35faa8143f70293"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "25cfd2f3e030fa3feaee2b50d8af64d873180d78"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4695e4a53d3c6c8ab4235fd606245c23044548f0e91cf48ed9ea175d74c20ab5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ccdd5cb9c9cd75a6f008f7bba6325acfbfb75b1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "b0312e593f2253d6485efdd057dbf5e3483024f6cb31f57857c8e71cb47d8a6b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b16c095c0c53b3509431b891e21cef95c4a476b0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "534892491b620470f61db57ea4bbb996cf3091b779b11b67b395c9f1a8887629"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e58a3d5d3582abda4e4e18509bba61078148db1f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "43bdc5a84b6f96805e65bfd141f63c1d0d6a92f54b031aa77ee867e7a2a46dbd"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d77d87bf064346ea2ff4f35c8e61cbf5a9cd49f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c02ea1d199b0b5ed303d2e8cfe83baea8a8c73df5b886f1c7664d40789931119"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2a85363813467bcf14fe754b13df4e7c0719affd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "923cebc1e59164304eaca6346898a6f6bf75461a0dd05325e21fc08dc62c0cdf"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7e3ec09d1e242c7d50f49d793e4e85860e3f0af6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ff18c8d18f66647b35a4222676f25f73096e75e0cda7263461841d18b1043406"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cc8ac8266e3d8ad3983e0f4bb8fe7f76c02f1b1f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "55c37441eea46f9655f990980aa236edcda6ca5774288d1b10dfe71baafb0764"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d7cd747882a4f93cf75d1f7f357ae9e670c699f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "b5590de6da5290c76d77f334fc3761e437bf0cb331b142d7cd26829919388b19"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "57fd23c12b2178b5adfc041e781ef54f22b11dd7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "b078b2e1b4dcf4a183a8c4a71df56b562550d7247774752a2fc8fe1199dc26ff"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eaa5119e65563d2966a4b8ddeca1ebd3fab4529c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "434f93ae93d7346b72f3af5b587e1c6c58bacbb580e1594e3a4dcc6a4598776d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6e1cb73b22452bf0f856ed10ff7f840a7cd88d67"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7d2b46176af4353259a57bd68d062eca7fdc471c3dd30846dc65d149a8b88557"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "816b623b4fadc13c69dcafdd41467dc2de6b0f0f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "445e3929475eb7c74530dc61ec012f43113b08df2dbb93f29eaf2d7015035697"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "a400464953be517a499e576b02473bf96b8eec36"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4839db9705b0911f1ff8322e263641f0323c721592cc7ae3d0df89d01b93679d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "a85189085df4bdef227bd5069275098855ec3b8b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a67133c9fe008ad9d9334f76616b315e6a222968a47e40740e9c776518ff7900"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "4adc0fe0ad88561f84c9d8160a6d90a618724260"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8b3c704339b40170a9a9d8f6ef4402c84074fbbe9b390d7542e3894a7b4a1887"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "e12c81a7f1319e9aabb64c6c0fe66df17a6d5988"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c9cd779851275c0127e422e5f22803f0a82efc01ac40482ea603806ff99e0afb"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "f372bec8a32bf5aa47823a5be4cb71967a22fe09"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "9719d24c7f1606a25b1bd123d85286d58e1280a679e5cb2114510b8a88675a07"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "9c829171fe106b8b002ad93eb3c069c82042e1bd"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "e7a3e0727daae1c8176e19e651a2d3614ae7d7a7de06db44e233cbec89338c1f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "94766a08bd9a06e4734a8e4f8b9c1663a6ddb3a1"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "58437632ef99eb1c6cad9670359f805699060ebd4590510885fd57d9ab29a823"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "45433f41f5afb5bb406d195c6a5d0ff7a6430aab"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "75f2fcee2d9f7be1ed8b93c49f1d815cfbac785f55428aada5e4cb49870224de"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "f24b96b2912f0c8135ab0a3a79888691c444c5ef"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7417440fb0841e17b8138befc17d9991799d23aba6d61b87c9cce584b33acb7d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "112405e869a5fc8ebebdc282d40ef816222100e3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "0032a89dafae2bfd4e3818427df94409d82d7fe9f569f4e4c5f750cff2cc1981"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "72d17b6e123f396558723b4be49195dbcfaae8fa"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "23a4c70971a1e7688326b551f4e45ecd677ef37966726bc86ef24f6bff155d9d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "f0612d977ae1fb6bb15667ddfd6e555e9920ed50"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "8c2c51f05d5924d58b902dc65ba294151b14efeb128a20c4129a825aafe8f327"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "8eaf59db4d14e0f65e52f3c8c62ec0f3fcb51397"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "bdbfd051cf2a620292bcc55e278d6ffbbeb5a762295d214239b92d7275f2a6cf"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "6eb16f3073b125fa110880355ba87d0812aa5685"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "e0de5f3895455cf2b68aa6331c45f7fa016d693fb5b2b6ba17aa1034e5dd01d8"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "28c435eaf573db220e87a8599e5024f8da20770c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "9b67ba7e230d43d87df044e5ce619f6ce753fd7c41b9502dea455c03752569c6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "9426b24f50168a4dafa082cc0c021c2b81c99d22"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "5b96b0a3899710a7816a78c5da2b1e9b6e566733699c8b7dc86efc79539c173c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "f41d1e6f29f4fb6b8aa0585936f6e8ccff4a3712"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "100b16aa190e8a5cad60aa2c39df63f14277b79ecaef377c44c03c6c14c84937"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "b46fe4e736357d0c2db5faa33c540b178cf8d4a0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "c8ecdbc1cf1aa8d4846b2f81dab604e4bf7bd9e0fd5c1b06a5ca69e896605bf9"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "97b72a6d634fd5a46322519e0477127057ab0f79"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f24c141f229d5b320480126cead9c6a7d7136f2b12bd18ca0c6f691a826a9b1a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "73ef278c3bbfdc9c36cce4591b924f8fd612c633"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "3cc3b2116b64ba0d2e05d2be177c2ad1670275de024c466ea8d548087f8e4151"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "9add9ca6cceee4d51ad6b6f56a3797ebfcb497c3"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "68e1fffe4a3aa0e1a2d33641e453198a9f33c7c07b2cf699fc596c3827616797"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "472b9c5acbadb657358a06cbe47c9a3812f255d7"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "8bf1b8d9e5acb7d253fd345dcab3d7167f5c6c7e6107d39ce5e83928d3d3220a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "c1cb90c4c9df061e6fbb23da6f7d2176921708bf"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "200b1f6998939be904beec09719e6c8f37b7fba51d7b800af6fec585cc89121d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "f3d0b01e7f77027100f77a197ebd05dd456f343b"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "49ad9d0004c1a38cedd145119b8e5001caac64c739dc21cac9441f7b154f6922"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "a1cadfd644a408be428933f526b16978c8d87582"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "38a7a15be89f595d1846c5b111e882b6f3f6c73cfc7e0ca24b64b96990d9b5ac"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "5ff80a5e537b924b030e37ac69883fc643b96745"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "1aee4947f06bc3f69035944592ea732745c99b4a3d224cb7ab649eba202f3577"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.5.1+2/Arpack.v3.5.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
