[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "87b6fe9f756585c40567136a5149f17b72856942"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "a5066473b9141f63e54e66db1442e99231bd6673eec4b9bbd470b8bb5916203f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "38dbd055fd3570d19ae48be0a15e653fd0c3fc40"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "65fab57826c8c0395eb0cee76ca999fbf608e8968993896c2fda27b8b4a76da9"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "185ae121d62e2029097090ac5f31a0a2fb02a8a8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "d630697371f8659a0cee38008ae140a98efb47a20329c87d78c3a3a234718e18"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "8a768a1cfdfef86ebf61ca034fc0eee723eab07a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "7ac1122486e7d2e056e478b3c6663c1fc6813b7ec00869ad60f30166790d2c92"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "a66e81004112072b195682e66bbc25029b75e2e0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "1a418f18f692792892b92849c44cc42bd4fee42c50833f1dd215c41ef4c4b9a4"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "11709fc5e4e62981d2bc1777377fc8a078ff1afe"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "2d4f9cf31218453747c33ca0fa778d1e0d11f083b68e05d77c699cbb82813053"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "aarch64"
git-tree-sha1 = "6a9dc789e68756f050a3539a8b00e32d02b426f3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "028f5aa9d59d81583b76bd43122b8c6e092a344846e036bd551be09079b4424d"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f815176392325cd02ba122da949bd5d206094108"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "59ee6e4146554d62c33384451d71b7ec4045f36d99105781ecee9d2cb02398a6"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "53567b801766ea374b28ffe7448259a085251f1a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "46d7e31b5939963f8546cdeb7ce64a8132ebd98dab848ced6c52bed2062142d3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6eaee545bdf1dbb346f5e22d538ff97580ff66e6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "9df278129df2a343402cc9a1e359df17614098d359733cf66f1189ce440bb2d3"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1e3e10985ed015594aa0777be284157c10532775"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "f275a86d36bfabb53f3d38d7685bb41a55a5c2de98ca7a21a6a0e713c00e0a13"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "332f38da2cdfdfda19247c55105484fd5e14d123"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ae39a81b96f648f6ab2e386715240c6342572376ab9d0aad988f1177d0ddb076"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9c8d2a51ecec2501c34264e91af7d93cb335e641"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "911d6d933a7f6e1c542a9db289b87ce6e52f5c5d5e038715db3b719cbe28c7a7"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d464a4e51241eb11777533348442dd265f2e200"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "08aac60d5d4c704474b7e5c7c07c661e8cc995700d10c762b61ad4695eb840ca"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "304cbd0858af459cdd71d2a63553182e99612da2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "41a27a00ff6a19a64885b93b476d7e57df0d405deef406482f7633605d68b413"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "01f5efe44d3cdfd2d1a120cfe682d52d2e686874"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "9e021280b68a6793ffb2016c63f218c260c94a3640417edc61967038e1549ada"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "284c4262fc236091065d3d9a83d611bf634e7bc5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "ba22228c7f7c5832469d5db3209493bb0326f53f5753cd5b318b6db2896dd5a1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aca122885b14e7619be5ca6b7a6a4c69dbaf9890"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "44b9f35ecffa3449bf0995c7abd54ed962f6b0176b9b6c2a67dcad21c13ed05b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Arpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9f195aa118f98580c06240231165a2b841650c13"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4e75749186317bcb039f8ed26a6b72b0197768bf4f62b6de6d50e14455d29442"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "ed1793cb2c9e1604578b3e6cc658907ccb582597"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "112014be3c11d9407b150292d291e7a9d257abe79e6c18684c1c6006efad80ad"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.i686-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "0592492d630daedeb2ce3ecce089487295692ff9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "205717f56b22fa6fcd008a1b9fd3a42d3d8acd248089431fd716797888b7534e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.i686-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "a6d4bfdaa84215014cf60efe315bb8755f6671f4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "e547099a5a70953eb1b55c4d5f5167603c4367b703ffbe65fe8aa26c0583c301"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.i686-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "a57771f620a08d772f3bdd1c6b6965c0d6467909"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "4ceaab071921c0154c1d747e8410e9e2e0d011491a310468a3ebfe64480d85ab"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.i686-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "2122b72961f0d0f903a2929642cd8e2f336c02d3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "3339e7d131b4ea7d981c80e14e67eb37acc6badce7f93c297811e9aa3db7f472"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.i686-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "1c12e97a01b9777960c5e2f25a2cf564cf028144"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "cfe5fae6ec183ddd699b909fe50bccdc559cf74f19339e568fa62a300487625a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.i686-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "33598534317fb2db086abcaa8c75376629c87026"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "785196bc655ecc90cfe796e2f02e6efc5ebd134f4fb321136fd3f957b1cab437"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "68572b384c3384255ae0dab08a4bd0259fc95d82"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "95a1b9389c53ec6605d27135efa1be9ce32f39fb10b8c277e3d7c3544c772afe"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "i686"
git-tree-sha1 = "06b6dae5634c95bcda81e3c5a042286528c3b0e0"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "18ac584637aa27196bbc3fc61171ff3137be504e3546e5616af4490227bfc325"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "4d0af62362188f606969bb8940cc5572b28bb2c0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "a39041a0713b27819752f2d534e55e73dfeab119db2c47ad24a72de57ab6a821"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "88003f0feb77103559cb839ace86a313b9722aef"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "578a13d2553f419bc03b2695235349b2e3cb5d0771bb6b92864c37d28045b65f"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "powerpc64le"
git-tree-sha1 = "71bb34586c3049784ab7f1165c03523af4cd5c1a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "fabfeb223e352f663112664cb261aa6b0af5dab45b8c9ae5a9b2c20b09319bfe"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "8a5942ced0d7e22ac43dfc46a6b036df0154899b"
libgfortran_version = "3.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "04a11d57d1e6f10b663db25c30ec53599edacc9d60893e0ba358be2e33b4bd19"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "5fada2d0173a54639f5b794e4f5a4ac72b969e11"
libgfortran_version = "4.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "3bc5be86cbbd600a3e0494660918c7d17d738a5e8402da1a83053ab56eca7d7c"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "15e18d7bd19dca8a5e11c9930549794e9ceac999"
libgfortran_version = "5.0.0"
os = "macos"

    [[Arpack.download]]
    sha256 = "70960ad604516348163ad0805480b5ca4280990b2488dc6158e1b5fe2d2aa320"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "0fee94a114c3e48df42f450b88e5920224b09ba2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "be1eb8b7329151181a34de05d9ea7768c0cdecbed37d1579ec42a938948c7a94"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "27264721eb90b0c1f4f830a60baf4b67eda0652e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "d208ba8066f6b9a3382fc31295ce2a98c88211456d39b6ed40d99ba2571b08d1"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "7a139ad052b997fc21e4b21dee9235516da5af1a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "dd15b5b17e83313735dc0febeffa5aa7967278a3a8fc92ca5c5261c28f46f802"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "f21c3e97079d4f9ebf8d14b1fc016d907a4ef93f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "fc4129863c1211148c56f004969c40c86a9ccbb659c4519188146e0e772a425b"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "4d3bc1169cf872d231f9cd229d0857bd65e1e283"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "60caba30bd6e4a3b4d25805e1b3c0706599b43243fb6e816262f747c5dcf49a5"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "4ccbe62f26d549afe9d4ef57f247a7338428c055"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Arpack.download]]
    sha256 = "8baaeeccbe908c85d05e36d9e8ed462e66ddaa870ea102f8fcfdf2104f073f6a"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "4e9c371a53f6b6aac3911b3c6fb71e953d303654"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "6eea2b99c08b14a76cae95a867b2c98bab55c2a2bea4816a8ff0bc7fe54255c9"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "bb14713d7448734cbc3755cf2df9832b924dce79"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "c7a0efa9fa1e98fb40014de833c6708985619c8d734fcb2b3e7cc92871c68d93"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "68f05c81ccf29decb9713a39aa266febb8dcf26a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Arpack.download]]
    sha256 = "269e1b8485a878ff25f926e3e8908a1f83e559c0e5bacffc35ec5da1ae27adc9"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "cbfe91adb50ecfaa584e329f0ba798e0a77b7232"
libgfortran_version = "3.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "8d9316357b3abafb17deac45bed5dd33dcdf5a6b6d0e355a9a3bbb3bc461486e"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "cb9e4aef9c60a1bc7a9013b84d355818ff24466e"
libgfortran_version = "4.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "efc0fd7b6259bcddfae7d646ceba000403ae542f5179aa9e11dd0a454697f8da"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Arpack]]
arch = "x86_64"
git-tree-sha1 = "b47e78b00ca29c89fcba1fe73c6f25f9d4572fd3"
libgfortran_version = "5.0.0"
os = "windows"

    [[Arpack.download]]
    sha256 = "5bfa15d2a2cc459dd9ac95dc9fc7a6604d203306816d29e5a693819eca1ec250"
    url = "https://github.com/JuliaBinaryWrappers/Arpack_jll.jl/releases/download/Arpack-v3.9.1+0/Arpack.v3.9.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
